export const bodyTypeMapping: { [key: string]: string } = {
    "SUV": "SUV",
    "suv": "SUV",
    "Sedan": "Sedan",
    "sedan": "Sedan",
    "Convertible": "Convertible",
    "convertible": "Convertible",
    "G Convertible": "Convertible",
    "G37 Convertible": "Convertible",
    "Q60 Convertible": "Convertible",
    "Beetle Convertible": "Convertible",
    "GranTurismo Convertible": "Convertible",
    "CTS-V Convertible": "Convertible",
    "Coupe": "Coupe",
    "G Coupe": "Coupe",
    "Genesis Coupe": "Coupe",
    "Elantra Coupe": "Coupe",
    "CTS Coupe": "Coupe",
    "G37 Coupe": "Coupe",
    "Q60 Coupe": "Coupe",
    "CTS-V Coupe": "Coupe",
    "Club Cab": "Cab",
    "Access Cab": "Cab",
    "Double Cab": "Cab",
    "Crew Cab": "Cab",
    "CrewMax Cab": "Cab",
    "Extended Cab": "Cab",
    "King Cab": "Cab",
    "SuperCrew": "Cab",
    "Regular Cab": "Cab",
    "SuperCab": "Cab",
    "Quad Cab": "Cab",
    "Mega Cab": "Cab",
    "Xtracab": "Cab",
    "Cab Plus": "Cab",
    "Cab Plus 4": "Cab",
    "Van": "Van",
    "van": "Van",
    "E-Series Van": "Van",
    "Transit Van": "Van",
    "Promaster Cargo Van": "Van",
    "Ram Van": "Van",
    "CTS Wagon": "Wagon",
    "Wagon": "Wagon",
    "CTS-V Wagon": "Wagon",
    "TSX Sport Wagon": "Wagon",
    "Minivan": "Minivan",
    "minivan": "Minivan"
};
